---
- name: "Include OS-specific tasks"
  include_tasks: "os/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/main.yml"

- name: Tune sysctl.conf for keepalive
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: "True"
  with_items:
    - { name: 'net.ipv4.tcp_keepalive_time', value: 60 }
    - { name: 'net.ipv4.tcp_keepalive_intvl', value: 10 }
    - { name: 'net.ipv4.tcp_keepalive_probes', value: 3 }
  tags:
    - config
  when: "'Linux' in ansible_system"
