[package]
name = "agent"
version = "0.4.0"
authors = ["The NOC Project"]
edition = "2018"
description = "NOC Agent"

[[bin]]
name = "noc-agent"
path = "src/main.rs"

[features]
default = [
    "cpu",
    "dns",
    "fs",
    "memory",
    "network",
    "test",
    "twamp-sender",
    "twamp-reflector",
    "uptime"
]
# cpu collector
cpu = ["systemstat"]
# dns collector
dns = ["trust-dns-proto"]
# fs collector
fs = ["systemstat"]
# memory collector
memory = ["systemstat"]
# network collector
network = ["systemstat"]
# test collector
test = []
# modbus_serial collector
# modbus_serial = []
# twamp-sender collector
twamp-sender = []
# twamp-reflector collector
twamp-reflector = []
# uptime collector
uptime = ["systemstat"]

[dependencies]
clap = "2.33"
log = "0.4"
env_logger = "0.8"
tokio = { version = "1.2", features = ["full"] }
bytes = "1.0"
trust-dns-resolver = "0.20"
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
async-trait = "0.1"
cfg-if = "1.0"
enum_dispatch = "0.3"
rand = "0.8"
lazy_static = "1.4"
chrono = "0.4"
thiserror = "1.0"
# Optional dependencies
trust-dns-proto = {version = "0.20", optional = true}
systemstat = {version = "0.1", optional = true}
# Subcrates for procedural macroses
agent-derive = {path = "libs/agent-derive"}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "twamp_benchmark"
harness = false

[[bench]]
name = "pktmodel_benchmark"
harness = false
