---
- name: Liftbridge tasks
  hosts: svc-liftbridge-exec
  become: "True"
  any_errors_fatal: "False"
  serial: 50%
  gather_facts: "True"
  tags:
    - liftbridge
  vars_files:
    - "../../vars/main.yml"
    - "../../vars/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  roles:
    - role: liftbridge
      when: liftbridge_complete is not defined
    - role: goss
      tags: [goss]
      vars:
        goss_service_name: liftbridge
  post_tasks:
    - name: set liftbridge complete
      set_fact:
        liftbridge_complete: "True"
