site_name: NOC Docs
site_description: NOC Documentation Project
site_author: The NOC Project
repo_url: https://code.getnoc.com/noc/noc/
repo_name: Gitlab
edit_uri: -/edit/master/docs/en
copyright: 2007-2020, The NOC Project
nav:
  - Home: index.md
  # - Installation:
  # - Quickstart
  - Administration Guide:
      - Configuration:
          - Overview: admin/config/index.md
          - Date and Time Formats: admin/datetime-format.md
          - Global Configuration: admin/config/global.md
          - "[activator] Section": admin/config/activator.md
          - "[audit] section": admin/config/audit.md
          - "[backup] section": admin/config/backup.md
          - "[bi] section": admin/config/bi.md
          - "[cache] section": admin/config/cache.md
          - "[card] section": admin/config/card.md
          - "[chwriter] section": admin/config/chwriter.md
          - "[classifier] section": admin/config/classifier.md
          - "[clickhouse] section": admin/config/clickhouse.md
          - "[consul] section": admin/config/consul.md
          - "[correlator] section": admin/config/correlator.md
          - "[customization] section": admin/config/customization.md
          - "[datasource] section": admin/config/datasource.md
          - "[datastream] section": admin/config/datastream.md
          - "[dcs] section": admin/config/dcs.md
          - "[discovery] section": admin/config/discovery.md
          - "[dns] section": admin/config/dns.md
          - "[escalator] section": admin/config/escalator.md
          - "[features] section": admin/config/features.md
          - "[fm] section": admin/config/fm.md
          - "[geocoding] section": admin/config/geocoding.md
          - "[gis] section": admin/config/gis.md
          - "[grafanads] section": admin/config/grafanads.md
          - "[help] section": admin/config/help.md
          - "[http_client] section": admin/config/http_client.md
          - "[initial] section": admin/config/initial.md
          - "[layout] section": admin/config/layout.md
          - "[logging] section": admin/config/logging.md
          - "[login] section": admin/config/login.md
          - "[mailsender] section": admin/config/mailsender.md
          - "[memcached] section": admin/config/memcached.md
          - "[metrics] section": admin/config/metrics.md
          - "[mongo] section": admin/config/mongo.md
          - "[mrt] section": admin/config/mrt.md
          - "[nbi] section": admin/config/nbi.md
          - "[nsqd] section": admin/config/nsqd.md
          - "[nsqlookupd] section": admin/config/nsqlookupd.md
          - "[path] section": admin/config/path.md
          - "[peer] section": admin/config/peer.md
          - "[pg] section": admin/config/pg.md
          - "[ping] section": admin/config/ping.md
          - "[pmwriter] section": admin/config/pmwriter.md
          - "[proxy] section": admin/config/proxy.md
          - "[redis] section": admin/config/redis.md
          - "[rpc] section": admin/config/rpc.md
          - "[sae] section": admin/config/sae.md
          - "[scheduler] section": admin/config/scheduler.md
          - "[script] section": admin/config/script.md
          - "[selfmon] section": admin/config/selfmon.md
          - "[sentry] section": admin/config/sentry.md
          - "[syslogcollector] section": admin/config/syslogcollector.md
          - "[tests] section": admin/config/tests.md
          - "[threadpool] section": admin/config/threadpool.md
          - "[traceback] section": admin/config/traceback.md
          - "[trapcollector] section": admin/config/trapcollector.md
          - "[web] section": admin/config/web.md
      - Internal Metrics: admin/internal-metrics.md
  - Reference:
      - Concepts:
          - Administrative Domain: reference/concepts/administrativedomain/index.md
          - API Key: reference/concepts/apikey/index.md
  #    - Capabilities:
  #   - Alarm Classes:
  #   - Event Classes:
  #   - Metric Types:
  #   - Model Interfaces:
  #   - Scripts:
  #   - Profiles:
  #   - Platforms:
  #   - Technologies:
  - Developer's Guide:
      - API:
          - Merge Request Labels: dev/mr-labels.md
          - DataStream:
              - Overview: dev/api/datastream/index.md
              - address: dev/api/datastream/address.md
              - administrativedomain: dev/api/datastream/administrativedomain.md
              - administrativedomain: dev/api/datastream/alarm.md
              - cfgping: dev/api/datastream/cfgping.md
              - cfgsyslog: dev/api/datastream/cfgsyslog.md
              - cfgtrap: dev/api/datastream/cfgtrap.md
              - dnszone: dev/api/datastream/dnszone.md
              - managedobject: dev/api/datastream/managedobject.md
              - dnszone: dev/api/datastream/dnszone.md
              - prefix: dev/api/datastream/prefix.md
              - resourcegroup: dev/api/datastream/resourcegroup.md
              - vrf: dev/api/datastream/vrf.md
          - NBI:
              - Overview: dev/api/nbi/index.md
              - config: dev/api/nbi/config.md
              - configrevisions: dev/api/nbi/configrevisions.md
              - getmappings: dev/api/nbi/getmappings.md
              - objectmetrics: dev/api/nbi/objectmetrics.md
              - objectstatus: dev/api/nbi/objectstatus.md
              - path: dev/api/nbi/path.md
              - telemetry: dev/api/nbi/telemetry.md
      - BI:
          - Dictionaries:
              - administrativedomain: dev/bi/dict/administrativedomain.md
              - alarmclass: dev/bi/dict/alarmclass.md
              - container: dev/bi/dict/container.md
              - interfacedescription: dev/bi/dict/interfacedescription.md
              - interfaceprofile: dev/bi/dict/interfaceprofile.md
              - managedobject: dev/bi/dict/managedobject.md
              - networksegment: dev/bi/dict/networksegment.md
              - platform: dev/bi/dict/platform.md
              - pool: dev/bi/dict/pool.md
              - profile: dev/bi/dict/profile.md
              - vendor: dev/bi/dict/vendor.md
              - version: dev/bi/dict/version.md
          - Models:
              - alarms: dev/bi/model/alarms.md
              - mac: dev/bi/model/mac.md
              - managedobjects: dev/bi/model/managedobjects.md
              - reboots: dev/bi/model/reboots.md
              - routingneighbors: dev/bi/model/routingneighbors.md
              - span: dev/bi/model/span.md
      - Inventory Protocols: dev/inventory-protocols.md
  #  - Man Pages:
  - HOWTO:
      - How to Share Collections: howto/sharing-collections/index.md
  - Releases:
      - NOC Release and Tagging Policy: releases/policy.md
      - NOC 0.1 Generation:
          - NOC 0.1RC1: releases/0.1rc1.md
          - NOC 0.1RC2: releases/0.1rc2.md
          - NOC 0.1: releases/0.1.md
  - About:
      - License: license.md
      - Contributing: contributing.md
      - Documentation Structure: structure.md
      - Style Guide: style-guide.md
theme: readthedocs
use_directory_urls: true
site_dir: ../../build/docs2/en
# strict: true
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
