site_name: NOC Docs
site_description: NOC Documentation Project
site_author: The NOC Project
repo_url: https://code.getnoc.com/noc/noc/
repo_name: Gitlab
edit_uri: -/edit/master/docs/en
copyright: 2007-2020, The NOC Project
nav:
  - Home: index.md
  # - Installation:
  # - Quickstart
  - Administration Guide:
      - Configuration:
          - Configuration System Overview: admin/config/index.md
          - Date and Time Formats: admin/datetime-format.md
          - Global Configuration: admin/config/global.md
          - "[activator] Section": admin/config/activator.md
          - "[audit] section": admin/config/audit.md
          - "[backup] section": admin/config/backup.md
          - "[bi] section": admin/config/bi.md
          - "[biosegmentation] section": admin/config/biosegmentation.md
          - "[cache] section": admin/config/cache.md
          - "[card] section": admin/config/card.md
          - "[chwriter] section": admin/config/chwriter.md
          - "[classifier] section": admin/config/classifier.md
          - "[clickhouse] section": admin/config/clickhouse.md
          - "[collections] section": admin/config/collections.md
          - "[consul] section": admin/config/consul.md
          - "[correlator] section": admin/config/correlator.md
          - "[customization] section": admin/config/customization.md
          - "[datasource] section": admin/config/datasource.md
          - "[datastream] section": admin/config/datastream.md
          - "[dcs] section": admin/config/dcs.md
          - "[discovery] section": admin/config/discovery.md
          - "[dns] section": admin/config/dns.md
          - "[escalator] section": admin/config/escalator.md
          - "[etl] section": admin/config/etl.md
          - "[features] section": admin/config/features.md
          - "[fm] section": admin/config/fm.md
          - "[geocoding] section": admin/config/geocoding.md
          - "[gis] section": admin/config/gis.md
          - "[grafanads] section": admin/config/grafanads.md
          - "[help] section": admin/config/help.md
          - "[http_client] section": admin/config/http_client.md
          - "[icqsender] section": admin/config/icqsender.md
          - "[initial] section": admin/config/initial.md
          - "[kafkasender] section": admin/config/kafkasender.md
          - "[layout] section": admin/config/layout.md
          - "[liftbridge] section": admin/config/liftbridge.md
          - "[logging] section": admin/config/logging.md
          - "[login] section": admin/config/login.md
          - "[mailsender] section": admin/config/mailsender.md
          - "[memcached] section": admin/config/memcached.md
          - "[message] section": admin/config/message.md
          - "[metrics] section": admin/config/metrics.md
          - "[mongo] section": admin/config/mongo.md
          - "[mrt] section": admin/config/mrt.md
          - "[nbi] section": admin/config/nbi.md
          - "[nsqd] section": admin/config/nsqd.md
          - "[nsqlookupd] section": admin/config/nsqlookupd.md
          - "[path] section": admin/config/path.md
          - "[peer] section": admin/config/peer.md
          - "[pg] section": admin/config/pg.md
          - "[ping] section": admin/config/ping.md
          - "[pmwriter] section": admin/config/pmwriter.md
          - "[proxy] section": admin/config/proxy.md
          - "[redis] section": admin/config/redis.md
          - "[rpc] section": admin/config/rpc.md
          - "[sae] section": admin/config/sae.md
          - "[scheduler] section": admin/config/scheduler.md
          - "[script] section": admin/config/script.md
          - "[selfmon] section": admin/config/selfmon.md
          - "[sentry] section": admin/config/sentry.md
          - "[syslogcollector] section": admin/config/syslogcollector.md
          - "[tests] section": admin/config/tests.md
          - "[tgsender] section": admin/config/tgsender.md
          - "[threadpool] section": admin/config/threadpool.md
          - "[traceback] section": admin/config/traceback.md
          - "[trapcollector] section": admin/config/trapcollector.md
          - "[web] section": admin/config/web.md
      - Discovery:
          - Box Discovery:
              - Overview: admin/discovery/box/index.md
              - Suggest SNMP: admin/discovery/box/suggestsnmp.md
              - Suggest CLI: admin/discovery/box/suggestcli.md
              - Profile: admin/discovery/box/profile.md
              - Version: admin/discovery/box/version.md
              - Caps: admin/discovery/box/caps.md
              - Asset: admin/discovery/box/asset.md
              - Interface: admin/discovery/box/interface.md
              - VRF: admin/discovery/box/vrf.md
              - VLAN: admin/discovery/box/vlan.md
              - SLA: admin/discovery/box/sla.md
              - ID: admin/discovery/box/id.md
              - Config: admin/discovery/box/config.md
              - CPE: admin/discovery/box/cpe.md
              - Segmentation: admin/discovery/box/segmentation.md
              - LLDP: admin/discovery/box/lldp.md
              - BFD: admin/discovery/box/bfd.md
              - CDP: admin/discovery/box/cdp.md
              - LACP: admin/discovery/box/lacp.md
              - OAM: admin/discovery/box/oam.md
              - FDP: admin/discovery/box/fdp.md
              - STP: admin/discovery/box/stp.md
              - REP: admin/discovery/box/rep.md
              - UDLD: admin/discovery/box/udld.md
              - Huawei NDP: admin/discovery/box/huawei_ndp.md
              - NRI: admin/discovery/box/nri.md
              - HouseKeeping: admin/discovery/box/hk.md
          - Periodic Discovery:
              - Overview: admin/discovery/periodic/index.md
          - AS Discovery:
              - Overview: admin/discovery/as/index.md
              - Prefix Discovery: admin/discovery/as/prefix.md
          - Segment Discovery:
              - Overview: admin/discovery/segment/index.md
              - MAC Discovery: admin/discovery/segment/mac.md
      - Internal Metrics: admin/internal-metrics.md
  - Reference:
      - Concepts:
          - Administrative Domain: reference/concepts/administrativedomain/index.md
          - API Key: reference/concepts/apikey/index.md
  #    - Capabilities:
  #   - Alarm Classes:
  #   - Event Classes:
  #   - Metric Types:
  #   - Model Interfaces:
  #   - Scripts:
  #   - Profiles:
  #   - Platforms:
  #   - Technologies:
  - Developer's Guide:
      - Merge Request Labels: dev/mr-labels.md
      - API:
          - DataStream:
              - Overview: dev/api/datastream/index.md
              - address: dev/api/datastream/address.md
              - administrativedomain: dev/api/datastream/administrativedomain.md
              - administrativedomain: dev/api/datastream/alarm.md
              - cfgping: dev/api/datastream/cfgping.md
              - cfgsyslog: dev/api/datastream/cfgsyslog.md
              - cfgtrap: dev/api/datastream/cfgtrap.md
              - dnszone: dev/api/datastream/dnszone.md
              - managedobject: dev/api/datastream/managedobject.md
              - dnszone: dev/api/datastream/dnszone.md
              - prefix: dev/api/datastream/prefix.md
              - resourcegroup: dev/api/datastream/resourcegroup.md
              - vrf: dev/api/datastream/vrf.md
          - NBI:
              - Overview: dev/api/nbi/index.md
              - config: dev/api/nbi/config.md
              - configrevisions: dev/api/nbi/configrevisions.md
              - getmappings: dev/api/nbi/getmappings.md
              - objectmetrics: dev/api/nbi/objectmetrics.md
              - objectstatus: dev/api/nbi/objectstatus.md
              - path: dev/api/nbi/path.md
              - telemetry: dev/api/nbi/telemetry.md
      - BI:
          - Dictionaries:
              - administrativedomain: dev/bi/dict/administrativedomain.md
              - alarmclass: dev/bi/dict/alarmclass.md
              - container: dev/bi/dict/container.md
              - interfacedescription: dev/bi/dict/interfacedescription.md
              - interfaceprofile: dev/bi/dict/interfaceprofile.md
              - managedobject: dev/bi/dict/managedobject.md
              - networksegment: dev/bi/dict/networksegment.md
              - platform: dev/bi/dict/platform.md
              - pool: dev/bi/dict/pool.md
              - profile: dev/bi/dict/profile.md
              - vendor: dev/bi/dict/vendor.md
              - version: dev/bi/dict/version.md
          - Models:
              - alarms: dev/bi/model/alarms.md
              - mac: dev/bi/model/mac.md
              - managedobjects: dev/bi/model/managedobjects.md
              - reboots: dev/bi/model/reboots.md
              - routingneighbors: dev/bi/model/routingneighbors.md
              - span: dev/bi/model/span.md
      - Handlers:
          - Config Filter: dev/handlers/config-filter.md
          - Config Diff Filter: dev/handlers/config-diff-filter.md
          - Window Function: dev/handlers/window-function.md
      - Model Interfaces:
          - airflow: dev/modelinterface/airflow.md
          - asset: dev/modelinterface/asset.md
          - contacts: dev/modelinterface/contacts.md
          - container: dev/modelinterface/container.md
          - cpu: dev/modelinterface/cpu.md
          - dimensions: dev/modelinterface/dimensions.md
          - geopint: dev/modelinterface/geopint.md
          - length: dev/modelinterface/length.md
          - management: dev/modelinterface/management.md
          - optical: dev/modelinterface/optical.md
          - plan: dev/modelinterface/plan.md
          - pop: dev/modelinterface/pop.md
          - power: dev/modelinterface/power.md
          - rack: dev/modelinterface/rack.md
          - rackmount: dev/modelinterface/rackmount.md
          - sector: dev/modelinterface/sector.md
          - splitter: dev/modelinterface/splitter.md
          - stack: dev/modelinterface/stack.md
          - twinax: dev/modelinterface/twinax.md
          - weight: dev/modelinterface/weight.md
      - Inventory Protocols: dev/inventory-protocols.md
      - ObjectModel Tags: dev/objectmodel-tags.md
  #  - Man Pages:
  - HOWTO:
      - How to Share Collections: howto/sharing-collections/index.md
  - Releases:
      - NOC Release and Tagging Policy: releases/policy.md
      - NOC 20.4 Generation:
          - NOC 20.4: releases/20.4.md
          - NOC 20.4.1: releases/20.4.1.md
      - NOC 20.3 Generation:
          - NOC 20.3: releases/20.3.md
          - NOC 20.3.1: releases/20.3.1.md
      - NOC 20.2 Generation:
          - NOC 20.2: releases/20.2.md
          - NOC 20.2.1: releases/20.2.1.md
          - NOC 20.2.2: releases/20.2.2.md
          - NOC 20.2.3: releases/20.2.3.md
      - NOC 20.1 Generation:
          - NOC 20.1: releases/20.1.md
          - NOC 20.1.1: releases/20.1.1.md
      - NOC 19.4 Generation:
          - NOC 19.4: releases/19.4.md
          - NOC 19.4.1: releases/19.4.1.md
          - NOC 19.4.2: releases/19.4.2.md
      - NOC 19.3 Generation:
          - NOC 19.3: releases/19.3.md
          - NOC 19.3.1: releases/19.3.1.md
          - NOC 19.3.2: releases/19.3.2.md
      - NOC 19.2 Generation:
          - NOC 19.2: releases/19.2.md
          - NOC 19.2.1: releases/19.2.1.md
          - NOC 19.2.2: releases/19.2.2.md
          - NOC 19.2.3: releases/19.2.3.md
      - NOC 19.1 Generation:
          - NOC 19.1: releases/19.1.md
          - NOC 19.1.1: releases/19.1.1.md
          - NOC 19.1.2: releases/19.1.2.md
          - NOC 19.1.3: releases/19.1.3.md
      - NOC 18 Generation:
          - NOC 18.1A1: releases/18.1A1.md
          - NOC 18.1.1: releases/18.1.1.md
      - NOC 15 Generation:
          - NOC 15.05: releases/15.05.md
          - NOC 15.05.1: releases/15.05.1.md
      - NOC 0.7 Generation:
          - NOC 0.7.1: releases/0.7.1.md
          - NOC 0.7.2: releases/0.7.2.md
          - NOC 0.7.3: releases/0.7.3.md
          - NOC 0.7.4: releases/0.7.4.md
      - NOC 0.6 Generation:
          - NOC 0.6: releases/0.6.md
          - NOC 0.6.1: releases/0.6.1.md
          - NOC 0.6.2: releases/0.6.2.md
          - NOC 0.6.3: releases/0.6.3.md
          - NOC 0.6.4: releases/0.6.4.md
      - NOC 0.5 Generation:
          - NOC 0.5: releases/0.5.md
          - NOC 0.5.1: releases/0.5.1.md
      - NOC 0.4 Generation:
          - NOC 0.4: releases/0.4.md
      - NOC 0.3 Generation:
          - NOC 0.3: releases/0.3.md
          - NOC 0.3.1: releases/0.3.1.md
          - NOC 0.3.2: releases/0.3.2.md
      - NOC 0.2 Generation:
          - NOC 0.2: releases/0.2.md
          - NOC 0.2.1: releases/0.2.1.md
          - NOC 0.2.2: releases/0.2.2.md
          - NOC 0.2.3: releases/0.2.3.md
          - NOC 0.2.4: releases/0.2.4.md
          - NOC 0.2.5: releases/0.2.5.md
          - NOC 0.2.6: releases/0.2.6.md
          - NOC 0.2.7: releases/0.2.7.md
      - NOC 0.1 Generation:
          - NOC 0.1RC1: releases/0.1rc1.md
          - NOC 0.1RC2: releases/0.1rc2.md
          - NOC 0.1: releases/0.1.md
          - NOC 0.1.1: releases/0.1.1.md
          - NOC 0.1.2: releases/0.1.2.md
          - NOC 0.1.3: releases/0.1.3.md
          - NOC 0.1.4: releases/0.1.4.md
          - NOC 0.1.5: releases/0.1.5.md
          - NOC 0.1.6: releases/0.1.6.md
          - NOC 0.1.7: releases/0.1.7.md
          - NOC 0.1.8: releases/0.1.8.md
          - NOC 0.1.9: releases/0.1.9.md
  - About:
      - License: license.md
      - Contributing: contributing.md
      - Documentation Structure: structure.md
      - Style Guide: style-guide.md
theme: material
use_directory_urls: true
site_dir: ../../build/docs2/en
# strict: true
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
plugins:
  - search
  - macros:
      module_name: macros
