---
# General settings
#
# for os specific see pre role
etc_prefix: /etc

# packages
grafana_version: "7.3.4"
grafana_plugin_simple_json_datasource_version: 1.4.0
grafana_plugin_clickhouse_datasource_version: 2.1.0
grafana_plugin_natel-discrete-panel_version: 0.1.0
nsq_version: "0.3.8"

consul_version: "1.8.6"
consul_template_version: "0.25.1"

tower_ip: 127.0.0.1
tower_path: /opt/tower
tower_dist_dir: "{{ tower_path }}/var/tower/data/src_dist"
tower_version: "{{ lookup('env','TOWER_VERSION') }}"
tower_show_secrets: "{{ not lookup('env','TOWER_SHOW_SECRETS') or False | bool }}"
tower_run_checks: "{{ lookup('env','TOWER_RUN_CHECKS') or False | bool }}"
tower_run_tests: "{{ lookup('env','TOWER_RUN_TESTS') or False | bool }}"
tower_stop_noc: "{{ lookup('env','TOWER_STOP_NOC') or True | bool }}"
tower_serial_restart_noc: "{{ lookup('env','TOWER_SERIAL_RESTART_NOC') or False | bool }}"
tower_minimum_version: "1.0.0"

noc_system_service: noc
mongo_dir: "{{ etc_prefix }}/mongod"
grafana_ini: "{{ etc_prefix }}/grafana/grafana.ini"

postgres_user: postgres

fake_shell: /bin/false
