---
- name: fail if noc is not selected
  fail:
    msg: "MX role have to be set with noc role to get own sources."
  when:
    - has_svc_mx is defined
    - has_svc_noc is not defined
  tags:
    - checks

- name: fail if liftbridge is not selected
  fail:
    msg: "MX service works only with liftbridge service. Please install at least one"
  when:
    - has_svc_mx is defined
    - "'svc-liftbridge' not in groups"
  tags:
    - checks
