---
- debug:
    msg: "GOSS_DEBUG"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  when: "goss_service_name" == "noc"

- name: place goss tests file for service {{ goss_service_name }}
  template:
    src: "{{ goss_service_name }}.goss.yml.j2"
    dest: "{{ goss_conf_dir }}/{{ goss_service_name }}.yml"
